server:
  port: 8070

spring:
  application:
    name: spring-reddit-clone
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/reddit_clone_db?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  #Mail configuration
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: ce10f8fcc34335
    password: f9343bf10c0bcc
    protocol: smtp